# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Development

on:
  push:
    branches: [ Development ]
  pull_request:
    branches: [ Development ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, chrome, firefox]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: Development
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install
        run: |
          npm install @dontcode/core@latest @dontcode/plugin-common@latest @dontcode/sandbox@latest --force
          npm ci
      - name: Build
        run: npm run build --if-present
      - name: E2E Tests on ${{matrix.browser}}
        run: |
          npm run ng e2e -- --browser ${{matrix.browser}}
      - uses: actions/upload-artifact@v2
        # Test run screenshots only on failure
        if: failure()
        with:
          name: cypress-screenshots
          path: dist/cypress/apps/preview-ui-e2e/screenshots
        # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: dist/cypress/apps/preview-ui-e2e/videos
